name: apexcharts
description: Apex Charts for Dart
version: 0.1.0
homepage: https://github.com/nigeltiany/apexcharts

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
